In [2]:
import numpy as np
array=[[[1,2,3],[4,5,6],[7,8,9]]]
a=np.array(array)
print(a)
a.size
a.shape
print(a)
a.ndim
a.dtype

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


dtype('int32')

In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [46]:
import numpy as np
sumit = np.array([])

sumit=np.insert(sumit,0,[41])
sumit1 =np.append(sumit,[42])
print(sumit1)


[41. 42.]


In [69]:
import numpy as np
a=np.array(['a','b'])
b =np.insert(a,a.size,3)
print(b)

['a' 'b' '3']


In [3]:
# Array Slicing and slecting
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [6]:
a=np.random.randint(5,size=(3,3))
a

array([[2, 4, 2],
       [2, 4, 0],
       [1, 1, 3]])

In [7]:
a[1:3,2:3]

array([[0],
       [3]])

In [ ]:
a[1:3,::]

In [26]:
a.sum()
a.sum(axis=0) # This is for ROW
a.sum(axis=1) # This is for coloumn
a.max(axis=0) # This is for ROW
a.max(axis=1) # This is for Coloumn
a.min()
a=np.transpose(a)
print(a.dtype)
a.dtype

int32


dtype('int32')

In [27]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)
arr.dtype

<U6


dtype('<U6')

In [32]:
np.append(a,100)
a.shape
a.ndim

2

In [35]:
np.append(a,[[6,6,6]],axis=0)

array([[2, 2, 1],
       [4, 4, 1],
       [2, 0, 3],
       [6, 6, 6]])

In [58]:
b=np.append(a,[[6],[6],[6]],axis=1)
b

array([[2, 2, 1, 6],
       [4, 4, 1, 6],
       [2, 0, 3, 6]])

In [47]:
a[a>2]
b[b>5]

array([6, 6, 6])

In [60]:
z=np.delete(b,3,axis=1)
z

array([[2, 2, 1],
       [4, 4, 1],
       [2, 0, 3]])

In [59]:
b

array([[2, 2, 1, 6],
       [4, 4, 1, 6],
       [2, 0, 3, 6]])